// Bundles the two sources of truth into one browser-loadable file.
//
//   public/data.json  -> window.VS_DATA     (the scores, untouched)
//   scoring.js        -> window.VS_ENGINE   (the exact engine, ES exports stripped)
//
// Why: the page must open straight off the filesystem (double-click index.html), and
// browsers refuse both fetch() and ES modules over file://. Classic <script> tags work.
// Generating the bundle instead of hand-copying means the page can never drift from the
// data or the engine that `npm run verify` checks.
//
//   npm run sync
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(ROOT, p), "utf8");

const dataRaw = read("public/data.json");
const engineRaw = read("scoring.js");

JSON.parse(dataRaw); // fail loudly on malformed data rather than shipping a broken page

const exported = [...engineRaw.matchAll(/^export\s+function\s+(\w+)/gm)].map((m) => m[1]);
if (!exported.length) throw new Error("scoring.js exports nothing — refusing to build");

const engineBody = engineRaw
  .replace(/^export\s+/gm, "")
  .trimEnd()
  .split("\n")
  .map((line) => (line ? "  " + line : ""))
  .join("\n");

const out = `/* AUTO-GENERATED by tools/build.mjs — do not edit.
 * Sources: public/data.json, scoring.js. Regenerate with \`npm run sync\`.
 * Verified against the Python engine by \`npm run verify\`. */
window.VS_DATA = ${dataRaw.trim()};

window.VS_ENGINE = (function () {
  "use strict";
${engineBody}
  return { ${exported.join(", ")} };
})();
`;

mkdirSync(join(ROOT, "assets"), { recursive: true });
writeFileSync(join(ROOT, "assets/generated.js"), out);

console.log(
  `assets/generated.js written — ${JSON.parse(dataRaw).vendors.length} vendors, ` +
  `engine exports: ${exported.join(", ")}`
);
